### ISSUE TITLE
Access denied to download

### ISSUE THREAD

**Issue by vadym-wix** [cvdfoundation/open-images-dataset#1]
I try to download images using indstruction and I get error for access denial

`AccessDeniedException: 403 #email# does not have storage.objects.list access to open-images-dataset.`

Also, during login I get this warning:
```
WARNING: `gcloud auth login` no longer writes application default credentials.
If you need to use ADC, see:
  gcloud auth application-default --help
```

**Comment by rkrasin** [comment]
Hi @vadym-wix!

Have you filled out this [registration form](http://www.cvdfoundation.org/datasets/open-images-dataset/signup.html)?

**Comment by vadym-wix** [comment]
@rkrasin , Thanks, that solved the issue :)
