### ISSUE TITLE
Clarity on switch from Google Storage to S3

### ISSUE THREAD

**Issue by ferrouswheel** [cvdfoundation/open-images-dataset#14]
I made [this comment on the commit](https://github.com/cvdfoundation/open-images-dataset/commit/39756643c6f6f52c0fe141d10c57fc9cf3e09305#commitcomment-29680139) that made the change, but posting it as an issue for visibility to the community.

The Google Storage URIs have been changed to Amazon S3 locations.

For those of us that are partway through syncing the training data from Google Storage - will it remain available?

I'm also curious in general what the reason for the switch is. Cheaper to host on S3 or are more people training models in AWS?

**Comment by tylin** [comment]
The Google Storage will still remain open. One can continue downloading data from Google Storage. The reason to create a copy on S3 is that AWS offers free Cloud service to support our efforts on distributing academia datasets publicly and freely.

**Comment by ferrouswheel** [comment]
Awesome. Thank you for the clarification :-)
