### ISSUE TITLE
Could you please upload a  copy to  Baidu Pan? 

### ISSUE THREAD

**Issue by superzrx** [cvdfoundation/open-images-dataset#15]
I`m suffering aws and google for it cannot resume downloading. Could you please upload the train set and test set to Baidu Pan? Thank you very much!

**Comment by tylin** [comment]
We currently do not have plan to copy data to Baidu. Using sync command should only download the remaining images.

**Comment by superzrx** [comment]
![image](https://user-images.githubusercontent.com/9104795/42935064-4ca7ceb0-8b7b-11e8-858b-607d062b9cd7.png)
it seems not working
