### ISSUE TITLE
Add 's3:GetBucketLocation' permission to AWS bucket

### ISSUE THREAD

**Issue by wpjohnson** [cvdfoundation/open-images-dataset#20]
Can you please add the IAM Permission ['s3:GetBucketLocation'](https://docs.aws.amazon.com/AmazonS3/latest/dev/using-with-s3-actions.html#using-with-s3-actions-related-to-bucket-subresources) in an [IAM Bucket Policy](https://docs.aws.amazon.com/AmazonS3/latest/dev/using-iam-policies.html) to the bounding box annotated dataset hosted on AWS S3 (s3://open-images-dataset)?

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "PublicPermissions",
            "Effect": "Allow",
            "Principal": "*",
            "Action": [
                "s3:GetBucketLocation"
            ],
            "Resource": [
                "arn:aws:s3:::open-images-dataset"
            ]
        }
    ]
}
```

Given the current ['public-read' ACL](https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html) present on the bucket, adding this permission doesn't expose any information that isn't already available. Specifically, the 's3:GetBucketLocation' permission only gives the bucket's 'x-amz-region', which is [already available from HEAD Bucket requests](https://forums.aws.amazon.com/message.jspa?messageID=705971) and used under-the-hood by the aws cli.

Granting this permission will allow for the use of [Google Cloud Storage Transfer Service](https://cloud.google.com/storage-transfer/docs/overview) to copy this dataset from AWS S3 to Google Cloud Storage (see my response in a separate open [issue](https://github.com/cvdfoundation/open-images-dataset/issues/18)).

**Comment by wpjohnson** [comment]
@tylin, as the most recent contributor to this repo, can you add this permission?

**Comment by tylin** [comment]
@wpjohnson, I added the permission. Could you give it a try for storage transfer to GCP?

**Comment by wpjohnson** [comment]
Just ran a transfer successfully using GCSTS, and it works! Thanks!
