### ISSUE TITLE
access to open images

### ISSUE THREAD

**Issue by arun-adiraju** [cvdfoundation/open-images-dataset#4]
how long will it take to provide the access after submitting form in the below link. Its been at least 3 hours i am not provided access. https://github.com/cvdfoundation/open-images-dataset/issues/3

**Comment by tylin** [comment]
You should have got access after you submit the form. Could you send me your gmail associated account?

**Comment by arun-adiraju** [comment]
I have the access now.

Thanks
Arun Adiraju
