### ISSUE TITLE
Download full dataset

### ISSUE THREAD

**Issue by yms6328** [cvdfoundation/open-images-dataset#7]
I want to download the full dataset (18TB) but I don't get the access permission.
I've already submitted CVDF access request.
I created google storage transfer but I got a message of 'permission denied', Can anyone tell me the way to download the full dataset?
help me plz! #

**Comment by tylin** [comment]
The full set can be downloaded via urls. You do not need to submit access request to access storage bucket. CVDF provides the tsv files to facilitate data transfer using Google Cloud Platform. Please follow the instruction in "Download Full Dataset With Google Storage Transfer" section.

**Comment by yms6328** [comment]
I got confused tsv url.
Thanks for your reply.

**Comment by YvanYin** [comment]
@tylin   Do you have a plan to transfer full data to AWS S3? Transferring the full data to Google Cloud storage and then downloading it to a local space is really expensive.
