### ISSUE TITLE
Missing training Images?

### ISSUE THREAD

**Issue by vs-zhehangd** [cvdfoundation/open-images-dataset#9]
Hi,

I only got 1592088 training images, one less than 1592089 according to the README. Is there something wrong? This number is also 1000+ less than what is provided in [here](https://github.com/openimages/dataset/blob/master/README.md#data-organization), which is 1,593,853.

Many Thanks

**Comment by tomasriv** [comment]
There are several missing image files if you iterate over the csv with the bounding boxes but nothing wrong, maybe an error when uploading it.
